name: Build

on:
  push:
    branches: [main, develop]
    tags: ['v?[0-9]+.[0-9]+.[0-9]+', 'v?[0-9]+.[0-9]+']
  pull_request:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: pre-commit/action@v3.0.0
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Prepare string for converting repo string to lowercase
      id: string
      uses: ASzc/change-string-case-action@v5
      with:
        string: ${{ github.repository }}
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ steps.string.outputs.lowercase }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    -
      name: Check required commands
      run: |
        set -e
        PRIMARY_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
        docker run -ti --rm ${PRIMARY_TAG} R --version
        docker run -ti --rm ${PRIMARY_TAG} Rscript --version
        docker run -ti --rm ${PRIMARY_TAG} alleleCounter --version
    -
      name: Prepare test data
      run: echo "this is where you'd load some test data"
